name: exp 
mode: train

runner: Pix2Style2Pix
dataset: I2I 

seed: 42

# Dataset setting
data_path: '../datasets/city2pixel/'
batch_size: 32 
num_workers: 0
image_norm: zero
image_size:
  - 256
  - 256
augment_type: default


epochs: 20

# Model setting
input_nc: 3
label_nc: 0
output_size: 1024
encoder_type: GradualStyleEncoder

# Loss setting
lpips_lambda: .8
id_lambda: 0
l2_lambda: 1.0
w_norm_lambda: 0.005
lpips_lambda_crop: 0
l2_lambda_crop: 0
moco_lambda: 0.5

moco_path: pretrained/moco_v2_800ep_pretrain.pt
ir_se50_path: pretrained/model_ir_se50.pth
stylegan_weights: pretrained/stylegan2-ffhq-config-f.pt 

learn_in_w: False 
start_from_latent_avg: True
train_decoder: True

# Optimizer setting
optimizer: adam
lr: 0.0001 
weight_decay: 0.000001 

# Logging setting
print_freq: 20
save_iter_freq: 5 

use_tensorboard: False 

# wandb setting
wandb_project: TEST 
wandb_resume_id: null 

init_weight: null
ckpt: null

exp_dir: null
