name: exp 
mode: train

runner: Pix2Pix
dataset: I2I 

seed: 42

# Dataset setting
data_path: '../datasets/city2pixel/'
batch_size: 64
num_workers: 0
image_norm: zero
image_size:
  - 256
  - 256
augment_type: default


save_iter_freq: 20
epochs: 20

# Model setting
disc: basic
ndf: 64
ngf: 64

# Loss setting
gan_loss: lsgan
lamb_gan: 1.0
lamb_rec: 10.0

# Optimizer setting
optimizer: adam
lr: 0.0001 
weight_decay: 0.000001 

# Scheduler setting
scheduler: null
lr_decay_iters: 50

# Logging setting
print_freq: 20
use_tensorboard: True

# wandb setting
wandb_project: null 
wandb_resume_id: null

init_weight: null
ckpt: null

exp_dir: null
