name: exp 
mode: train

runner: Pix2Pix
dataset: Selfie2Anime

seed: 42

data_path: '../datasets/selfie2anime/'
batch_size: 64
num_workers: 3
image_norm: 'zero'
image_size:
  - 256
  - 256
augment_type: 'default'


save_iter_freq: 20
epochs: 20

disc: 'basic'
ndf: 64
ngf: 64

gan_loss: 'lsgan'
lamb_gan: 1.0
lamb_rec: 10.0

optimizer: 'adam'
lr: 0.0001 
weight_decay: 0.000001 

scheduler: null
lr_decay_iters: 50

exp_dir: null

init_weight: null
ckpt: null
